export interface Country {
  name: string;
  code: string;
}

export const wc26Teams: Country[] = [
  { name: 'Algeria', code: 'ALG' },
  { name: 'Argentina', code: 'ARG' },
  { name: 'Australia', code: 'AUS' },
  { name: 'Austria', code: 'AUT' },
  { name: 'Belgium', code: 'BEL' },
  { name: 'Bosnia and Herzegovina', code: 'BIH' },
  { name: 'Brazil', code: 'BRA' },
  { name: 'Canada', code: 'CAN' },
  { name: 'Cape Verde', code: 'CPV' },
  { name: 'Colombia', code: 'COL' },
  { name: 'Croatia', code: 'CRO' },
  { name: 'Curaçao', code: 'CUW' },
  { name: 'Czech Republic', code: 'CZE' },
  { name: 'DR Congo', code: 'COD' },
  { name: 'Ecuador', code: 'ECU' },
  { name: 'Egypt', code: 'EGY' },
  { name: 'England', code: 'ENG' },
  { name: 'France', code: 'FRA' },
  { name: 'Germany', code: 'GER' },
  { name: 'Ghana', code: 'GHA' },
  { name: 'Haiti', code: 'HAI' },
  { name: 'Iran', code: 'IRN' },
  { name: 'Iraq', code: 'IRQ' },
  { name: 'Italy', code: 'ITA' },
  { name: 'Ivory Coast', code: 'CIV' },
  { name: 'Japan', code: 'JPN' },
  { name: 'Jordan', code: 'JOR' },
  { name: 'Mexico', code: 'MEX' },
  { name: 'Morocco', code: 'MAR' },
  { name: 'Netherlands', code: 'NED' },
  { name: 'New Zealand', code: 'NZL' },
  { name: 'Norway', code: 'NOR' },
  { name: 'Panama', code: 'PAN' },
  { name: 'Paraguay', code: 'PAR' },
  { name: 'Poland', code: 'POL' },
  { name: 'Portugal', code: 'POR' },
  { name: 'Qatar', code: 'QAT' },
  { name: 'Saudi Arabia', code: 'KSA' },
  { name: 'Scotland', code: 'SCO' },
  { name: 'Senegal', code: 'SEN' },
  { name: 'South Africa', code: 'RSA' },
  { name: 'South Korea', code: 'KOR' },
  { name: 'Spain', code: 'ESP' },
  { name: 'Sweden', code: 'SWE' },
  { name: 'Switzerland', code: 'SUI' },
  { name: 'Tunisia', code: 'TUN' },
  { name: 'Turkey', code: 'TUR' },
  { name: 'Uruguay', code: 'URU' },
  { name: 'USA', code: 'USA' },
  { name: 'Uzbekistan', code: 'UZB' }
];
