CREATE TABLE IF NOT EXISTS public.stickers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nationality character varying(255) COLLATE pg_catalog."default",
    place character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stickers_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.stickers
    OWNER to admin;

CREATE TABLE IF NOT EXISTS public.owning
(
    id bigint NOT NULL DEFAULT nextval('owning_id_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT owning_pkey PRIMARY KEY (id),
    CONSTRAINT unique_email_code UNIQUE (email, code)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.owning
    OWNER to admin;


CREATE TABLE duplicates (
                            id BIGSERIAL PRIMARY KEY,
                            email VARCHAR(255) NOT NULL,
                            code VARCHAR(100) NOT NULL,
                            number INTEGER NOT NULL,
                            created_at TIMESTAMPTZ DEFAULT NOW(),

                            CONSTRAINT unique_email_code_number UNIQUE (email, code, number)
);

